var class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample =
[
    [ "ReadEeprom", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample_1_1_read_eeprom.html", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample_1_1_read_eeprom" ],
    [ "WriteEeprom", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample_1_1_write_eeprom.html", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample_1_1_write_eeprom" ]
];