var class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample =
[
    [ "ApplySettings", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_apply_settings.html", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_apply_settings" ],
    [ "RebootDevice", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_reboot_device.html", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_reboot_device" ],
    [ "RestoreFactoryDefaults", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_restore_factory_defaults.html", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_restore_factory_defaults" ]
];