var hierarchy =
[
    [ "HidGlobal.OK.Readers.AViatoR.Components.ApplySettings", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_apply_settings.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderConfigurationControlSample.ApplySettings", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_apply_settings.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.CharacterDiff", "struct_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_character_diff.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.CharacterDifferencesCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_c1f38bf6c7f8d063ec140f81ac2c55ee.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.ConfigurationCardSecurityKeyUpdateCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_6488de03e187660d6ce4b6e081dc2618.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.ConfigurationCardSupportCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_eb8626796db31dc5819367b215fa48a8.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.ConfigurationCardWriteDataCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_3e123ade4fe7b0367fa7601ba341984a.html", null ],
    [ "HidGlobal.OK.Readers.Components.ConnectionStatus", "struct_hid_global_1_1_o_k_1_1_readers_1_1_components_1_1_connection_status.html", null ],
    [ "HidGlobal.OK.Readers.WinSCard.WinSCardWrapper.ConnectionStatus", "struct_hid_global_1_1_o_k_1_1_readers_1_1_win_s_card_1_1_win_s_card_wrapper_1_1_connection_status.html", null ],
    [ "HidGlobal.OK.Readers.WinSCard.WinSCardWrapper.ConnectResult", "struct_hid_global_1_1_o_k_1_1_readers_1_1_win_s_card_1_1_win_s_card_wrapper_1_1_connect_result.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ContactCardCommunication", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_contact_card_communication.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ContactlessCardCommunication", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_contactless_card_communication.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ContactlessCardCommunicationV2", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_contactless_card_communication_v2.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ContactSlotConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_contact_slot_configuration.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ContactSlotEnable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_contact_slot_enable.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeAConfigurationSample.CredentialEnable", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_a_configuration_sample_1_1_credential_enable.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeBConfigurationSample.CredentialEnable", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_b_configuration_sample_1_1_credential_enable.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.FelicaConfigurationSample.CredentialEnable", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_felica_configuration_sample_1_1_credential_enable.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.CredentialTypeCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_credential_type_command.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.DecrementCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_decrement_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic.DecrementMifareClassic1kExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic_1_1_decrement_mifare_classic1k_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic.DecrementMifareClassic1kForOK5023Example", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic_1_1_decr9d0cf0684464f032f3d1e8ccd5dfe057.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.DeviceId", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_device_id.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.DeviceId", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_device_id.html", null ],
    [ "KbwToCcidSwitchApi.NativeLibraries.Wrapper.DevPropKey", "struct_kbw_to_ccid_switch_api_1_1_native_libraries_1_1_wrapper_1_1_dev_prop_key.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.EmdSuppresionEnable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_emd_suppresion_enable.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.EnabledClFeatures", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_enabled_cl_features.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.EnabledClFeatures", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_enabled_cl_features.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.SEProcessorSample.ExampleBase", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_s_e_processor_sample_1_1_example_base.html", [
      [ "HidGlobal.OK.SampleCodes.AViatoR.SEProcessorSample.DesfireFormatCardExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_s_e_processor_sample_1_1_desfire_format_card_example.html", null ],
      [ "HidGlobal.OK.SampleCodes.AViatoR.SEProcessorSample.DesfireReadWriteDataExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_s_e_processor_sample_1_1_desfire_read_write_data_example.html", null ],
      [ "HidGlobal.OK.SampleCodes.AViatoR.SEProcessorSample.LoadKeyExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_s_e_processor_sample_1_1_load_key_example.html", null ],
      [ "HidGlobal.OK.SampleCodes.AViatoR.SEProcessorSample.ReadPACSDataExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_s_e_processor_sample_1_1_read_p_a_c_s_data_example.html", null ]
    ] ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithIso15693", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_iso15693.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ExchangeLevel", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_exchange_level.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.ExchangeLevel", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_exchange_level.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.ExtendedCharacterSupportCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_b016a84bec7a7cd758d18d4351406a14.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.FelicaConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_felica_configuration.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.FelicaConfigurationSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_felica_configuration_sample.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.FelicaEnable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_felica_enable.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.FelicaRxTxBaudRate", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_felica_rx_tx_baud_rate.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.FirmwareLabel", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_firmware_label.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.FirmwareLabel", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_firmware_label.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.FirmwareVersion", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_firmware_version.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.FirmwareVersion", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_firmware_version.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.GeneralAuthenticateCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_general_authenticate_command.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.GetDataCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_data_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.GetDataExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_get_data_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.GetHistoricalBytesExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_get_historical_bytes_example.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.HardwareVersion", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_hardware_version.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.HardwareVersion", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_hardware_version.html", null ],
    [ "HashAlgorithm", null, [
      [ "HidGlobal.OK.Readers.Utilities.CrcX25Algorithm", "class_hid_global_1_1_o_k_1_1_readers_1_1_utilities_1_1_crc_x25_algorithm.html", null ]
    ] ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.HfControllerType", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_hf_controller_type.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.HfControllerType", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_hf_controller_type.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.HfControllerVersion", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_hf_controller_version.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.HfControllerVersion", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_hf_controller_version.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.HostInterfaces", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_host_interfaces.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.HostInterfaces", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_host_interfaces.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.HumanInterfaces", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_human_interfaces.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.HumanInterfaces", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_human_interfaces.html", null ],
    [ "HidGlobal.OK.Readers.IApduCommand", "interface_hid_global_1_1_o_k_1_1_readers_1_1_i_apdu_command.html", [
      [ "HidGlobal.OK.Readers.ApduCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_apdu_command.html", null ]
    ] ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.iClass15693Enable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1i_class15693_enable.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.iClassConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1i_class_configuration.html", null ],
    [ "HidGlobal.OK.SampleCodes.Utilities.IConsoleWriter", "interface_hid_global_1_1_o_k_1_1_sample_codes_1_1_utilities_1_1_i_console_writer.html", [
      [ "HidGlobal.OK.SampleCodes.Utilities.ConsoleWriter", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_utilities_1_1_console_writer.html", null ]
    ] ],
    [ "ICryptoTransform", null, [
      [ "HidGlobal.OK.Readers.SecureSession.CounterModeCryptoTransform", "class_hid_global_1_1_o_k_1_1_readers_1_1_secure_session_1_1_counter_mode_crypto_transform.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardSupport.IConfigurationCard", "interface_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_support_1_1_i_configuration_card.html", [
        [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardSupport.ConfigurationCard", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_support_1_1_configuration_card.html", null ]
      ] ],
      [ "HidGlobal.OK.Readers.IContextHandler", "interface_hid_global_1_1_o_k_1_1_readers_1_1_i_context_handler.html", [
        [ "HidGlobal.OK.Readers.ContextHandler", "class_hid_global_1_1_o_k_1_1_readers_1_1_context_handler.html", null ]
      ] ],
      [ "HidGlobal.OK.Readers.ISmartCardReader", "interface_hid_global_1_1_o_k_1_1_readers_1_1_i_smart_card_reader.html", [
        [ "HidGlobal.OK.Readers.SmartCardReader", "class_hid_global_1_1_o_k_1_1_readers_1_1_smart_card_reader.html", null ]
      ] ],
      [ "HidGlobal.OK.Readers.SecureSession.ISecureChannel", "interface_hid_global_1_1_o_k_1_1_readers_1_1_secure_session_1_1_i_secure_channel.html", [
        [ "HidGlobal.OK.Readers.SecureSession.SamSecureSession.SamSecureSession", "class_hid_global_1_1_o_k_1_1_readers_1_1_secure_session_1_1_sam_secure_session_1_1_sam_secure_session.html", null ],
        [ "HidGlobal.OK.Readers.SecureSession.SecureChannel", "class_hid_global_1_1_o_k_1_1_readers_1_1_secure_session_1_1_secure_channel.html", null ]
      ] ]
    ] ],
    [ "IEnumerable", null, [
      [ "HidGlobal.OK.Readers.Components.BaudRate", "struct_hid_global_1_1_o_k_1_1_readers_1_1_components_1_1_baud_rate.html", null ],
      [ "KbwToCcidSwitchApi.KeyboardData", "struct_kbw_to_ccid_switch_api_1_1_keyboard_data.html", null ]
    ] ],
    [ "KbwToCcidSwitchApi.FeatureReport.IFeatureReport", "interface_kbw_to_ccid_switch_api_1_1_feature_report_1_1_i_feature_report.html", [
      [ "KbwToCcidSwitchApi.FeatureReport.FeatureReport", "class_kbw_to_ccid_switch_api_1_1_feature_report_1_1_feature_report.html", null ]
    ] ],
    [ "KbwToCcidSwitchApi.Discovery.IKeyboardDiscovery", "interface_kbw_to_ccid_switch_api_1_1_discovery_1_1_i_keyboard_discovery.html", [
      [ "KbwToCcidSwitchApi.Discovery.KeyboardDiscovery", "class_kbw_to_ccid_switch_api_1_1_discovery_1_1_keyboard_discovery.html", null ]
    ] ],
    [ "HidGlobal.OK.Readers.ILengthField", "interface_hid_global_1_1_o_k_1_1_readers_1_1_i_length_field.html", null ],
    [ "HidGlobal.OK.SampleCodes.MenuSections.IMenuItem", "interface_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_i_menu_item.html", [
      [ "HidGlobal.OK.SampleCodes.MenuSections.MenuItem", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_menu_item.html", null ]
    ] ],
    [ "HidGlobal.OK.SampleCodes.MenuSections.IMenuSection", "interface_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_i_menu_section.html", [
      [ "HidGlobal.OK.SampleCodes.MenuSections.KeyboardWedgesMenuSection", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_keyboard_wedges_menu_section.html", null ],
      [ "HidGlobal.OK.SampleCodes.MenuSections.OK5022MenuSection", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_o_k5022_menu_section.html", null ],
      [ "HidGlobal.OK.SampleCodes.MenuSections.OK5023MenuSection", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_o_k5023_menu_section.html", null ],
      [ "HidGlobal.OK.SampleCodes.MenuSections.OK5027MenuSection", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_o_k5027_menu_section.html", null ],
      [ "HidGlobal.OK.SampleCodes.MenuSections.Ok5122MenuSection", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_ok5122_menu_section.html", null ],
      [ "HidGlobal.OK.SampleCodes.MenuSections.Ok5422MenuSection", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_ok5422_menu_section.html", null ],
      [ "HidGlobal.OK.SampleCodes.MenuSections.SmartCardReadersMenuSection", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_smart_card_readers_menu_section.html", null ]
    ] ],
    [ "HidGlobal.OK.SampleCodes.MenuSections.IMenuSectionsFactory", "interface_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_i_menu_sections_factory.html", [
      [ "HidGlobal.OK.SampleCodes.MenuSections.KeyboardWedgesMenuFactory", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_keyboard_wedges_menu_factory.html", null ],
      [ "HidGlobal.OK.SampleCodes.MenuSections.SmartCardReadersMenuFactory", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_menu_sections_1_1_smart_card_readers_menu_factory.html", null ]
    ] ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.IncrementCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_increment_command.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.IncrementDecrementCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_increment_decrement_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic.IncrementMifareClassic1kExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic_1_1_increment_mifare_classic1k_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic.IncrementMifareClassic1kForOK5023Example", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic_1_1_incr2a6bf1b215e04862ba0d1e4662cc5b11.html", null ],
    [ "HidGlobal.OK.Readers.Components.IoRequest", "struct_hid_global_1_1_o_k_1_1_readers_1_1_components_1_1_io_request.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso14443TypeAConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso14443_type_a_configuration.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeAConfigurationSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_a_configuration_sample.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso14443TypeAEnable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso14443_type_a_enable.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso14443TypeARxTxBaudRate", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso14443_type_a_rx_tx_baud_rate.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso14443TypeBConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso14443_type_b_configuration.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeBConfigurationSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_b_configuration_sample.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso14443TypeBEnable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso14443_type_b_enable.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso14443TypeBRxTxBaudRate", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso14443_type_b_rx_tx_baud_rate.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso15693Configuration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso15693_configuration.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Iso15693Enable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_iso15693_enable.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.KeyboardLayoutCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_keyboard_layout_command.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.KeyboardWedgeConfigCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_keyboard_wedge_config_command.html", [
      [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardInitializationCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_initialization_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardSecurityKeyUpdateCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_security_key_update_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardWriteDataCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_write_data_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetConfigurationCardSupportEnabledCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_configuration_card_support_enabled_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeCardTypeCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_card_type_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeCharactersDiffCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_characters_diff_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeKeyboardLayoutCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_keyboard_layout_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeOutputFlagsCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_output_flags_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeOutputFormatCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_output_format_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgePostStrokesStartCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_post_strokes_start_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgePrePostStrokesCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_pre_post_strokes_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeRangeLengthCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_range_length_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeRangeStartCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_range_start_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeSupportForExtendedCharsCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_support_for_extended_chars_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetLedIdleStateCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_led_idle_state_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetConfigurationCardSupportEnabledCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_configuration_card_support_enabled_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeCardTypeCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_card_type_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeCharactersDiffCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_characters_diff_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeKeyboardLayoutCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_keyboard_layout_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeOutputFlagsCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_output_flags_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeOutputFormatCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_output_format_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgePostStrokesStartCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_post_strokes_start_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgePrePostStrokesCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_pre_post_strokes_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeRangeLengthCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_range_length_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeRangeStartCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_range_start_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetKeyboardWedgeSupportForExtendedCharsCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_keyboard_wedge_support_for_extended_chars_command.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.SetLedIdleStateCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_set_led_idle_state_command.html", null ]
    ] ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.KeyboardWedgeConfigCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_keyboard_wedge_config_command_response.html", [
      [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardInitializationCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_initialization_command_response.html", [
        [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardSecurityKeyUpdateCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_security_key_update_command_response.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.ConfigurationCardWriteDataCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_configuration_card_write_data_command_response.html", null ]
      ] ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetConfigurationCardSupportEnabledCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_configuration_card_support_enabled_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeCardTypeCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_card_type_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeCharactersDiffCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_characters_diff_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeKeyboardLayoutCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_keyboard_layout_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeOutputFlagsCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_output_flags_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeOutputFormatCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_output_format_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgePostStrokesStartCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_post_strokes_start_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgePrePostStrokesCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_pre_post_strokes_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeRangeLengthCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_range_length_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeRangeStartCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_range_start_command_response.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetKeyboardWedgeSupportForExtendedCharsCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_keyboard_wedge_support1a139df325083574e856e2b26705adcc.html", null ],
      [ "HidGlobal.OK.Readers.AViatoR.Components.GetLedIdleStateCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_get_led_idle_state_command_response.html", null ]
    ] ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.LedIdleStateCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_led_idle_state_command.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.LoadKeyCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_load_key_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic.LoadKeyExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic_1_1_load_key_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.SEProcessorSample.LoadKeyToPcScContainer", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_s_e_processor_sample_1_1_load_key_to_pc_sc_container.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.LoadKeyToPcScContainerExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_load_key_to_pc_sc_container_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeAConfigurationSample.MifareEmulationPreferred", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_a_configuration_sample_1_1_mifare_emulation_preferred.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.MifareKeyCache", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_mifare_key_cache.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeAConfigurationSample.MifareKeyCache", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_a_configuration_sample_1_1_mifare_key_cache.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.MifarePreferred", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_mifare_preferred.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.NumberOfAntennas", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_number_of_antennas.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.NumberOfAntennas", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_number_of_antennas.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.NumberOfContactlessSlots", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_number_of_contactless_slots.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.NumberOfContactlessSlots", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_number_of_contactless_slots.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.NumberOfContactSlots", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_number_of_contact_slots.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.NumberOfContactSlots", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_number_of_contact_slots.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5022", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5022.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5022ContactlessCommon", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5022_contactless_common.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5022ContactlessSlotConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5022_contactless_slot_configuration.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5023", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5023.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5023ContactlessCommon", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5023_contactless_common.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5023ContactlessSlotConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5023_contactless_slot_configuration.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5422", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5422.html", [
      [ "HidGlobal.OK.Readers.AViatoR.Components.OK5122", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_o_k5122.html", null ]
    ] ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5422ContactlessCommon", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5422_contactless_common.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.OK5422ContactlessSlotConfiguration", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_o_k5422_contactless_slot_configuration.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.OperatingMode", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_operating_mode.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.OutputFlagsCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_output_flags_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.OutputFormatCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_output_format_command.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.PollingRFModuleEnable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_polling_r_f_module_enable.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.PollingSearchOrderConfig", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_polling_search_order_config.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.PostStrokesStartCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_post_strokes_start_command.html", null ],
    [ "HidGlobal.OK.Readers.Utilities.PrePostStrokesBuilder", "class_hid_global_1_1_o_k_1_1_readers_1_1_utilities_1_1_pre_post_strokes_builder.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.PrePostStrokesCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_pre_post_strokes_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.ProductName", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_product_name.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ProductName", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_product_name.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ProductPlatform", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_product_platform.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.ProductPlatform", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_product_platform.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.RangeLengthCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_range_length_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.KeyboardWedgeConfigurationSample.RangeOffsetCommand", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_keyboard_wedge_configuration_sample_1_1_range_offset_command.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ReadBinaryCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_read_binary_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.ReadBinaryiClass16kExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_read_binaryi_class16k_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.ReadBinaryiClass16kOK5023Example", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_read_binaryi_class16k_o_k5023_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.ReadBinaryiClass2ksExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_read_binaryi_class2ks_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.ReadBinaryiClass2ksOK5023Example", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_read_binaryi_class2ks_o_k5023_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic.ReadBinaryMifareClassic1kExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic_1_1_reada04d3328de103df75953ec48288e828b.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithIso15693.ReadBinaryNXPiCode", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_iso15693_1_1_read_binary_n_x_pi_code.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderEepromSample.ReadEeprom", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample_1_1_read_eeprom.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ReaderCapabilities", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_reader_capabilities.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ReaderConfigurationControl", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_reader_configuration_control.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderConfigurationControlSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ReaderEeprom", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_reader_eeprom.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderEepromSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample.html", null ],
    [ "HidGlobal.OK.Readers.Components.ReaderState", "struct_hid_global_1_1_o_k_1_1_readers_1_1_components_1_1_reader_state.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderConfigurationControlSample.RebootDevice", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_reboot_device.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.RebootDevice", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_reboot_device.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.ResotoreFactoryDefaults", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_resotore_factory_defaults.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderConfigurationControlSample.RestoreFactoryDefaults", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_configuration_control_sample_1_1_restore_factory_defaults.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeBConfigurationSample.RxTxBaudRate", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_b_configuration_sample_1_1_rx_tx_baud_rate.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.FelicaConfigurationSample.RxTxBaudRate", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_felica_configuration_sample_1_1_rx_tx_baud_rate.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.Iso14443TypeAConfigurationSample.RxTxBaudRate", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_iso14443_type_a_configuration_sample_1_1_rx_tx_baud_rate.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.SEPCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_command.html", [
      [ "HidGlobal.OK.Readers.AViatoR.Components.SEPCommandCommonBase", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_command_common_base.html", [
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireAuthNative", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_auth_native.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireCreateApplication", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_create_application.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireCreateStandardDataFile", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_create_standard_data_file.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireFormatCard", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_format_card.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireReadData", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_read_data.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireSelectApplication", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_select_application.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireWriteData", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_write_data.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPLoadKey", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_load_key.html", null ],
        [ "HidGlobal.OK.Readers.AViatoR.Components.SEPReadPACSData", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_read_p_a_c_s_data.html", null ]
      ] ]
    ] ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.SEPCommand.SEPCommandResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_command_1_1_s_e_p_command_response.html", [
      [ "HidGlobal.OK.Readers.AViatoR.Components.SEPReadPACSData.SEPReadPACSDataResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_read_p_a_c_s_data_1_99943fb838b887f10172683c41c1f9d5.html", null ]
    ] ],
    [ "SEPCommandResponse", null, [
      [ "HidGlobal.OK.Readers.AViatoR.Components.SEPDESFireReadData.SEPDESFireReadDataResponse", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_s_e_p_d_e_s_fire_read_dataf955382045e42933a8e9c11076af0a4d.html", null ]
    ] ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.SEProcessorSample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_s_e_processor_sample.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.SerialNumber", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_serial_number.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.SerialNumber", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_serial_number.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.SizeOfUserEeprom", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_size_of_user_eeprom.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.SizeOfUserEEPROM", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_size_of_user_e_e_p_r_o_m.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.SleepModeCardDetectionEnable", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_sleep_mode_card_detection_enable.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.SleepModePollingFrequency", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_sleep_mode_polling_frequency.html", null ],
    [ "SymmetricAlgorithm", null, [
      [ "HidGlobal.OK.Readers.SecureSession.AesCounterMode", "class_hid_global_1_1_o_k_1_1_readers_1_1_secure_session_1_1_aes_counter_mode.html", null ]
    ] ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Synchronus2WBP", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_synchronus2_w_b_p.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.Synchronus3WBP", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_synchronus3_w_b_p.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.SynchronusI2C", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_synchronus_i2_c.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.TlvVersion", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_tlv_version.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.TlvVersion", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_tlv_version.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.UpdateBinaryCommand", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_update_binary_command.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.UpdateBinaryiClass16kExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_update_binaryi_class16k_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.UpdateBinaryiClass16kOK5023Example", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_update_binaryi_class16k_o_k5023_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.UpdateBinaryiClass2ksExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_update_binaryi_class2ks_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithiClass.UpdateBinaryiClass2ksOK5023Example", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_withi_class_1_1_update_binaryi_class2ks_o_k5023_example.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithMifareClassic.UpdateBinaryMifareClassic1kExample", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_mifare_classic_1_1_updac051e1b42a3a25d85b63419f4f886471.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ExampleWithIso15693.UpdateBinaryNXPiCode", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_example_with_iso15693_1_1_update_binary_n_x_pi_code.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.VendorName", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_vendor_name.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.VendorName", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_vendor_name.html", null ],
    [ "HidGlobal.OK.Readers.AViatoR.Components.VoltageSequence", "class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_voltage_sequence.html", null ],
    [ "HidGlobal.OK.SampleCodes.AViatoR.ReaderEepromSample.WriteEeprom", "class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_eeprom_sample_1_1_write_eeprom.html", null ]
];