var searchData=
[
  ['featurereport',['FeatureReport',['../class_kbw_to_ccid_switch_api_1_1_feature_report_1_1_feature_report.html',1,'KbwToCcidSwitchApi::FeatureReport']]],
  ['felicaconfiguration',['FelicaConfiguration',['../class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_felica_configuration.html',1,'HidGlobal::OK::Readers::AViatoR::Components']]],
  ['felicaconfigurationsample',['FelicaConfigurationSample',['../class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_felica_configuration_sample.html',1,'HidGlobal::OK::SampleCodes::AViatoR']]],
  ['felicaenable',['FelicaEnable',['../class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_felica_enable.html',1,'HidGlobal::OK::Readers::AViatoR::Components']]],
  ['felicarxtxbaudrate',['FelicaRxTxBaudRate',['../class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_felica_rx_tx_baud_rate.html',1,'HidGlobal::OK::Readers::AViatoR::Components']]],
  ['firmwarelabel',['FirmwareLabel',['../class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_firmware_label.html',1,'HidGlobal.OK.Readers.AViatoR.Components.FirmwareLabel'],['../class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_firmware_label.html',1,'HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.FirmwareLabel']]],
  ['firmwareversion',['FirmwareVersion',['../class_hid_global_1_1_o_k_1_1_readers_1_1_a_viato_r_1_1_components_1_1_firmware_version.html',1,'HidGlobal.OK.Readers.AViatoR.Components.FirmwareVersion'],['../class_hid_global_1_1_o_k_1_1_sample_codes_1_1_a_viato_r_1_1_reader_capabilities_sample_1_1_firmware_version.html',1,'HidGlobal.OK.SampleCodes.AViatoR.ReaderCapabilitiesSample.FirmwareVersion']]],
  ['forgetreader',['ForgetReader',['../class_hid_global_1_1_o_k_1_1_readers_1_1_context_handler.html#a54beed65b9d3bc0c4477b4e513bfc68b',1,'HidGlobal.OK.Readers.ContextHandler.ForgetReader()'],['../interface_hid_global_1_1_o_k_1_1_readers_1_1_i_context_handler.html#a91c801d1cdee9dc085cd933971951277',1,'HidGlobal.OK.Readers.IContextHandler.ForgetReader()']]],
  ['forgetreadergroup',['ForgetReaderGroup',['../class_hid_global_1_1_o_k_1_1_readers_1_1_context_handler.html#a07c0ea729973272f222d3101b62d76f1',1,'HidGlobal.OK.Readers.ContextHandler.ForgetReaderGroup()'],['../interface_hid_global_1_1_o_k_1_1_readers_1_1_i_context_handler.html#aa97e2241d739490f3d7a2583242b197c',1,'HidGlobal.OK.Readers.IContextHandler.ForgetReaderGroup()']]]
];
